import {
  Zap,
  ShieldCheck,
  Bot,
  Rocket,
  Globe,
  Heart,
  ShoppingCart,
  Truck,
  MessageCircle,
  Building2,
  GraduationCap,
  CreditCard,
  Plane,
  Factory,
  Fuel,
  Music,
  Package,
  Home,
  DollarSign,
  Smartphone,
} from "lucide-react";

export interface Metric {
  value: number;
  suffix: string;
  label: string;
}

export interface TimelineStep {
  phase: string;
  detail: string;
}

export interface Project {
  id: string;
  tag: string;
  tagColor: string;
  company: string;
  industry: string;
  industrySlug: string;
  headline: string;
  challenge: string;
  solution: string;
  duration: string;
  Icon: React.ElementType;
  metrics: Metric[];
  timeline: TimelineStep[];
  gradient: string;
  accentColor: string;
}

export interface Industry {
  slug: string;
  label: string;
  Icon: React.ElementType;
}

export const industries: Industry[] = [
  { slug: "all", label: "All Projects", Icon: Globe },
  { slug: "healthcare-lifesciences", label: "Healthcare & Lifesciences", Icon: Heart },
  { slug: "ecommerce-solutions", label: "E-Commerce Solutions", Icon: ShoppingCart },
  { slug: "transport-logistics", label: "Transport & Logistics", Icon: Truck },
  { slug: "social-networking", label: "Social Networking", Icon: MessageCircle },
  { slug: "real-estate", label: "Real Estate", Icon: Building2 },
  { slug: "education-elearning", label: "Education & eLearning", Icon: GraduationCap },
  { slug: "banking-finance-insurance", label: "Banking, Finance & Insurance", Icon: CreditCard },
  { slug: "travel-hospitality", label: "Travel & Hospitality", Icon: Plane },
  { slug: "enterprise-retail-manufacturing", label: "Enterprise Retail & Manufacturing", Icon: Factory },
  { slug: "oil-gas", label: "Oil & Gas", Icon: Fuel },
  { slug: "media-entertainment", label: "Media & Entertainment", Icon: Music },
  { slug: "on-demand-delivery", label: "On Demand Delivery", Icon: Package },
  { slug: "home-service", label: "Home Service", Icon: Home },
  { slug: "fintech", label: "Fintech", Icon: DollarSign },
  { slug: "mcommerce", label: "mCommerce", Icon: Smartphone },
];

export const projects: Project[] = [
  // Healthcare & Lifesciences
  {
    id: "chorus-health",
    tag: "Cross-Platform App",
    tagColor: "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
    company: "CHORUS",
    industry: "Healthcare & Lifesciences",
    industrySlug: "healthcare-lifesciences",
    headline: "Cross-platform healthcare app for Google with real-time patient vitals monitoring.",
    challenge: "Inconsistent BLE performance across platforms. Real-time data synchronization. Maintaining healthcare-grade data security.",
    solution: "Built CHORUS, a scalable cross-platform application (Web, Android, iOS). Tracks live patient vitals such as heart rate and oxygen levels via BLE. Implements secure architecture with SAST, SCA, and rigorous testing.",
    duration: "120 days",
    Icon: Heart,
    metrics: [
      { value: 99.9, suffix: "%", label: "Uptime achieved" },
      { value: 3, suffix: " platforms", label: "Web, Android, iOS" },
      { value: 0, suffix: " breaches", label: "Security incidents" },
    ],
    timeline: [
      { phase: "Platform Architecture", detail: "Cross-platform framework selection, BLE protocol design" },
      { phase: "Vitals Integration", detail: "Real-time heart rate, oxygen level tracking" },
      { phase: "Security Hardening", detail: "SAST, SCA scanning, healthcare-grade encryption" },
      { phase: "Multi-Platform Launch", detail: "Synchronized release across Web, Android, iOS" },
    ],
    gradient: "from-emerald-600/10 via-transparent to-transparent",
    accentColor: "#10b981",
  },
  {
    id: "medicore-ehr",
    tag: "EHR System",
    tagColor: "bg-teal-500/15 text-teal-400 border-teal-500/30",
    company: "MediCore",
    industry: "Healthcare & Lifesciences",
    industrySlug: "healthcare-lifesciences",
    headline: "HIPAA-compliant electronic health records system for 500+ healthcare providers.",
    challenge: "Legacy paper-based records causing delays. Strict HIPAA compliance requirements. Integration with existing hospital systems.",
    solution: "Cloud-native EHR with end-to-end encryption, audit logging, and role-based access. Seamless HL7 FHIR integration with lab systems and pharmacies.",
    duration: "90 days",
    Icon: ShieldCheck,
    metrics: [
      { value: 500, suffix: "+", label: "Providers onboarded" },
      { value: 100, suffix: "%", label: "HIPAA compliance" },
      { value: 60, suffix: "%", label: "Record access time cut" },
    ],
    timeline: [
      { phase: "Compliance Framework", detail: "HIPAA controls, encryption, audit trail design" },
      { phase: "EHR Core Build", detail: "Patient records, prescriptions, lab results modules" },
      { phase: "Integration Layer", detail: "HL7 FHIR APIs, pharmacy & lab system connectors" },
      { phase: "Provider Rollout", detail: "Phased onboarding, training, and 24/7 support" },
    ],
    gradient: "from-teal-600/10 via-transparent to-transparent",
    accentColor: "#14b8a6",
  },
  // E-Commerce Solutions
  {
    id: "cartflow-ecom",
    tag: "Headless Commerce",
    tagColor: "bg-violet-500/15 text-violet-400 border-violet-500/30",
    company: "CartFlow",
    industry: "E-Commerce Solutions",
    industrySlug: "ecommerce-solutions",
    headline: "AI-powered headless commerce platform driving 38% increase in average order value.",
    challenge: "Generic product suggestions leading to 71% cart abandonment. No real-time ML infrastructure for personalization.",
    solution: "Built a headless commerce platform with real-time ML recommendation engine using TensorFlow Serving. Multi-currency support and dynamic pricing.",
    duration: "60 days",
    Icon: ShoppingCart,
    metrics: [
      { value: 38, suffix: "%", label: "AOV increase" },
      { value: 22, suffix: "%", label: "Abandonment drop" },
      { value: 18, suffix: "ms", label: "Inference latency" },
    ],
    timeline: [
      { phase: "Data Pipeline", detail: "Kafka streams for clickstream and purchase history" },
      { phase: "ML Model Training", detail: "Collaborative filtering + content-based hybrid" },
      { phase: "API & Caching Layer", detail: "Spring Boot serving TF models with Redis caching" },
      { phase: "Rollout & Tuning", detail: "Canary at 5% → 100% with feature-flag control" },
    ],
    gradient: "from-violet-600/10 via-transparent to-transparent",
    accentColor: "#8b5cf6",
  },
  {
    id: "shopnest-marketplace",
    tag: "Multi-Vendor Marketplace",
    tagColor: "bg-purple-500/15 text-purple-400 border-purple-500/30",
    company: "ShopNest",
    industry: "E-Commerce Solutions",
    industrySlug: "ecommerce-solutions",
    headline: "Scalable multi-vendor marketplace supporting 10K+ sellers with real-time inventory.",
    challenge: "Managing inventory across thousands of vendors. Payment splitting and commission tracking. Real-time order synchronization.",
    solution: "Microservices-based marketplace with event-driven inventory management. Automated payment splitting with Stripe Connect and real-time order tracking.",
    duration: "75 days",
    Icon: Rocket,
    metrics: [
      { value: 10, suffix: "K+", label: "Active sellers" },
      { value: 99.5, suffix: "%", label: "Order accuracy" },
      { value: 2, suffix: "s", label: "Sync latency" },
    ],
    timeline: [
      { phase: "Marketplace Architecture", detail: "Multi-tenant design, vendor onboarding flow" },
      { phase: "Inventory Engine", detail: "Event-driven stock management across vendors" },
      { phase: "Payments & Splits", detail: "Stripe Connect integration, automated commissions" },
      { phase: "Launch & Scale", detail: "Load testing, CDN setup, monitoring dashboards" },
    ],
    gradient: "from-purple-600/10 via-transparent to-transparent",
    accentColor: "#a855f7",
  },
  // Transport & Logistics
  {
    id: "fleettrack-logistics",
    tag: "Fleet Management",
    tagColor: "bg-[#4EB3E8]/15 text-[#4a7db8] border-[#4EB3E8]/30",
    company: "FleetTrack",
    industry: "Transport & Logistics",
    industrySlug: "transport-logistics",
    headline: "IoT-powered fleet management system reducing fuel costs by 25% across 2000+ vehicles.",
    challenge: "No real-time visibility into vehicle locations. Manual route planning causing inefficiency. High fuel costs due to unoptimized routes.",
    solution: "GPS + IoT sensor integration for real-time fleet tracking. AI-based route optimization engine. Predictive maintenance alerts reducing breakdowns by 40%.",
    duration: "90 days",
    Icon: Truck,
    metrics: [
      { value: 25, suffix: "%", label: "Fuel cost reduction" },
      { value: 2000, suffix: "+", label: "Vehicles tracked" },
      { value: 40, suffix: "%", label: "Fewer breakdowns" },
    ],
    timeline: [
      { phase: "IoT Integration", detail: "GPS trackers, fuel sensors, OBD-II device setup" },
      { phase: "Tracking Platform", detail: "Real-time dashboard with geofencing and alerts" },
      { phase: "Route Optimization", detail: "AI-based routing engine with traffic data" },
      { phase: "Predictive Maintenance", detail: "ML models for breakdown prediction" },
    ],
    gradient: "from-[#1a4a7a]/10 via-transparent to-transparent",
    accentColor: "#4EB3E8",
  },
  {
    id: "shipwise-supply",
    tag: "Supply Chain",
    tagColor: "bg-cyan-500/15 text-cyan-400 border-cyan-500/30",
    company: "ShipWise",
    industry: "Transport & Logistics",
    industrySlug: "transport-logistics",
    headline: "End-to-end supply chain visibility platform cutting delivery delays by 35%.",
    challenge: "Fragmented supply chain with no unified tracking. Manual documentation causing delays. Poor vendor communication.",
    solution: "Unified platform connecting warehouses, carriers, and vendors. Automated documentation with OCR. Real-time shipment tracking with ETA predictions.",
    duration: "60 days",
    Icon: Zap,
    metrics: [
      { value: 35, suffix: "%", label: "Delay reduction" },
      { value: 90, suffix: "%", label: "Doc automation" },
      { value: 50, suffix: "+", label: "Vendor integrations" },
    ],
    timeline: [
      { phase: "Platform Design", detail: "Unified tracking architecture, API gateway" },
      { phase: "Vendor Integration", detail: "50+ carrier and warehouse API connections" },
      { phase: "Automation Layer", detail: "OCR for documents, automated status updates" },
      { phase: "Analytics Dashboard", detail: "Real-time KPIs, delay prediction models" },
    ],
    gradient: "from-cyan-600/10 via-transparent to-transparent",
    accentColor: "#06b6d4",
  },
  // Social Networking
  {
    id: "connecthub-social",
    tag: "Community Platform",
    tagColor: "bg-pink-500/15 text-pink-400 border-pink-500/30",
    company: "ConnectHub",
    industry: "Social Networking",
    industrySlug: "social-networking",
    headline: "Community platform scaling to 500K users with real-time messaging and content feeds.",
    challenge: "Building a low-latency real-time messaging system. Content moderation at scale. Handling viral content spikes.",
    solution: "WebSocket-based real-time messaging with Redis pub/sub. AI content moderation pipeline. Auto-scaling infrastructure on AWS with CDN distribution.",
    duration: "75 days",
    Icon: MessageCircle,
    metrics: [
      { value: 500, suffix: "K", label: "Active users" },
      { value: 15, suffix: "ms", label: "Message latency" },
      { value: 99.8, suffix: "%", label: "Content accuracy" },
    ],
    timeline: [
      { phase: "Core Social Engine", detail: "User profiles, connections, activity feeds" },
      { phase: "Real-Time Messaging", detail: "WebSocket infrastructure, Redis pub/sub" },
      { phase: "AI Moderation", detail: "Content filtering, toxicity detection pipeline" },
      { phase: "Scale & CDN", detail: "Auto-scaling, CDN distribution, load testing" },
    ],
    gradient: "from-pink-600/10 via-transparent to-transparent",
    accentColor: "#ec4899",
  },
  {
    id: "teamspace-collab",
    tag: "Collaboration Tool",
    tagColor: "bg-rose-500/15 text-rose-400 border-rose-500/30",
    company: "TeamSpace",
    industry: "Social Networking",
    industrySlug: "social-networking",
    headline: "Enterprise collaboration platform with video calls, channels, and file sharing for 50K+ teams.",
    challenge: "Integrating video conferencing with chat. End-to-end encryption for enterprise security. Cross-platform desktop and mobile apps.",
    solution: "WebRTC-based video with selective forwarding unit. E2E encrypted messaging. Electron desktop app + React Native mobile apps.",
    duration: "100 days",
    Icon: Bot,
    metrics: [
      { value: 50, suffix: "K+", label: "Teams onboarded" },
      { value: 100, suffix: "%", label: "E2E encrypted" },
      { value: 4, suffix: " platforms", label: "Web, Desktop, iOS, Android" },
    ],
    timeline: [
      { phase: "Chat Infrastructure", detail: "E2E encrypted channels, threads, reactions" },
      { phase: "Video Integration", detail: "WebRTC with SFU for group calls" },
      { phase: "File & Search", detail: "Cloud storage integration, full-text search" },
      { phase: "Cross-Platform Launch", detail: "Electron, React Native, progressive web app" },
    ],
    gradient: "from-rose-600/10 via-transparent to-transparent",
    accentColor: "#f43f5e",
  },
  // Real Estate
  {
    id: "propview-realestate",
    tag: "PropTech Platform",
    tagColor: "bg-amber-500/15 text-amber-400 border-amber-500/30",
    company: "PropView",
    industry: "Real Estate",
    industrySlug: "real-estate",
    headline: "AI-powered property listing platform with virtual tours and smart valuation.",
    challenge: "Manual property valuation processes. No virtual viewing capability. Scattered listing data across multiple platforms.",
    solution: "Unified listing aggregation with AI-based property valuation. 360° virtual tour integration. Smart search with neighborhood analytics.",
    duration: "70 days",
    Icon: Building2,
    metrics: [
      { value: 45, suffix: "%", label: "Faster valuations" },
      { value: 25, suffix: "K+", label: "Listings managed" },
      { value: 3, suffix: "x", label: "Lead conversion" },
    ],
    timeline: [
      { phase: "Data Aggregation", detail: "Multi-source listing ingestion, normalization" },
      { phase: "AI Valuation Engine", detail: "ML models for property price prediction" },
      { phase: "Virtual Tours", detail: "360° media upload, WebGL-based viewer" },
      { phase: "Smart Search", detail: "Neighborhood analytics, commute scoring" },
    ],
    gradient: "from-amber-600/10 via-transparent to-transparent",
    accentColor: "#f59e0b",
  },
  {
    id: "rentease-mgmt",
    tag: "Property Management",
    tagColor: "bg-orange-500/15 text-orange-400 border-orange-500/30",
    company: "RentEase",
    industry: "Real Estate",
    industrySlug: "real-estate",
    headline: "Automated property management platform handling 15K+ rental units with zero paperwork.",
    challenge: "Manual rent collection and lease management. Maintenance request tracking chaos. Tenant screening bottlenecks.",
    solution: "Automated rent collection with ACH/card payments. Digital lease signing. AI-based tenant screening and maintenance ticketing system.",
    duration: "55 days",
    Icon: Rocket,
    metrics: [
      { value: 15, suffix: "K+", label: "Units managed" },
      { value: 95, suffix: "%", label: "On-time rent" },
      { value: 0, suffix: " paper", label: "Fully digital" },
    ],
    timeline: [
      { phase: "Payment Automation", detail: "ACH, card processing, automated reminders" },
      { phase: "Lease Management", detail: "Digital signing, renewal workflows" },
      { phase: "Maintenance System", detail: "Ticketing, vendor dispatch, photo uploads" },
      { phase: "Tenant Screening", detail: "AI-based credit and background checks" },
    ],
    gradient: "from-orange-600/10 via-transparent to-transparent",
    accentColor: "#f97316",
  },
  // Education & eLearning
  {
    id: "edtech-ai-learn",
    tag: "AI-Driven Platform",
    tagColor: "bg-indigo-500/15 text-indigo-400 border-indigo-500/30",
    company: "LearnAI",
    industry: "Education & eLearning",
    industrySlug: "education-elearning",
    headline: "AI-driven e-learning platform with personalized learning paths and live classes.",
    challenge: "Creating scalable AI for personalized learning. Real-time performance for live classes. Balancing gamification with academic rigor.",
    solution: "Web and mobile platform with AI-driven course recommendations. Live class functionality using WebRTC. Gamification features for engagement.",
    duration: "90 days",
    Icon: GraduationCap,
    metrics: [
      { value: 45, suffix: "%", label: "Learner improvement" },
      { value: 3, suffix: "x", label: "Engagement increase" },
      { value: 10, suffix: "K+", label: "Active students" },
    ],
    timeline: [
      { phase: "AI Model Design", detail: "Adaptive learning algorithm, recommendation engine" },
      { phase: "Live Class Engine", detail: "WebRTC for real-time video and collaboration" },
      { phase: "Gamification", detail: "Points, badges, leaderboards" },
      { phase: "Scale & Launch", detail: "Multi-tenant deployment, analytics" },
    ],
    gradient: "from-indigo-600/10 via-transparent to-transparent",
    accentColor: "#6366f1",
  },
  {
    id: "skillbridge-lms",
    tag: "LMS Platform",
    tagColor: "bg-sky-500/15 text-sky-400 border-sky-500/30",
    company: "SkillBridge",
    industry: "Education & eLearning",
    industrySlug: "education-elearning",
    headline: "Enterprise LMS serving 200+ companies with SCORM-compliant course delivery.",
    challenge: "SCORM compliance across diverse content. Multi-tenant white-label requirements. Offline learning support for remote areas.",
    solution: "SCORM 2004 compliant engine with offline-first PWA. White-label theming per organization. Advanced analytics for learning outcomes.",
    duration: "80 days",
    Icon: Bot,
    metrics: [
      { value: 200, suffix: "+", label: "Companies served" },
      { value: 100, suffix: "%", label: "SCORM compliant" },
      { value: 30, suffix: "%", label: "Completion rate up" },
    ],
    timeline: [
      { phase: "SCORM Engine", detail: "Content packaging, tracking, bookmarking" },
      { phase: "White-Label System", detail: "Per-org theming, branding, domain mapping" },
      { phase: "Offline PWA", detail: "Service workers, content caching, sync" },
      { phase: "Analytics Suite", detail: "Learning outcomes, engagement dashboards" },
    ],
    gradient: "from-sky-600/10 via-transparent to-transparent",
    accentColor: "#0ea5e9",
  },
  // Banking, Finance & Insurance
  {
    id: "finapp-ai",
    tag: "AI-Powered Finance",
    tagColor: "bg-[#4EB3E8]/15 text-[#4a7db8] border-[#4EB3E8]/30",
    company: "FinSmart",
    industry: "Banking, Finance & Insurance",
    industrySlug: "banking-finance-insurance",
    headline: "AI-powered financial management app with fraud detection and smart budgeting.",
    challenge: "Secure handling of sensitive financial data. Building accurate AI models for fraud detection.",
    solution: "Cross-platform app with bank-grade encryption, biometric auth. ML algorithms for spending analysis and anomaly detection. Seamless digital wallet integration.",
    duration: "80 days",
    Icon: CreditCard,
    metrics: [
      { value: 95, suffix: "%", label: "Fraud detection rate" },
      { value: 40, suffix: "%", label: "Better money mgmt" },
      { value: 100, suffix: "%", label: "Data encryption" },
    ],
    timeline: [
      { phase: "Security Architecture", detail: "Bank-grade encryption, biometric auth" },
      { phase: "AI Model Training", detail: "Spending analysis, anomaly detection" },
      { phase: "Payment Integration", detail: "Digital wallets, payment gateways" },
      { phase: "Launch & Monitor", detail: "Cross-platform release, fraud monitoring" },
    ],
    gradient: "from-[#1a4a7a]/10 via-transparent to-transparent",
    accentColor: "#4EB3E8",
  },
  {
    id: "insuretech-claims",
    tag: "InsurTech",
    tagColor: "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
    company: "ClaimFast",
    industry: "Banking, Finance & Insurance",
    industrySlug: "banking-finance-insurance",
    headline: "Automated insurance claims processing reducing settlement time from 30 days to 48 hours.",
    challenge: "Manual claims processing causing month-long delays. Document verification bottlenecks. Fraudulent claims costing millions.",
    solution: "AI-powered document extraction with OCR. Automated fraud scoring with ML. Digital-first claims journey with real-time status tracking.",
    duration: "65 days",
    Icon: Zap,
    metrics: [
      { value: 97, suffix: "%", label: "Processing automated" },
      { value: 48, suffix: " hrs", label: "Avg settlement" },
      { value: 85, suffix: "%", label: "Fraud caught" },
    ],
    timeline: [
      { phase: "OCR Pipeline", detail: "Document extraction, classification, validation" },
      { phase: "Fraud Detection", detail: "ML scoring model, pattern recognition" },
      { phase: "Claims Workflow", detail: "Digital-first journey, automated approvals" },
      { phase: "Integration & Launch", detail: "Core insurance system connectors" },
    ],
    gradient: "from-emerald-600/10 via-transparent to-transparent",
    accentColor: "#10b981",
  },
  // Travel & Hospitality
  {
    id: "bookwise-travel",
    tag: "Booking Platform",
    tagColor: "bg-sky-500/15 text-sky-400 border-sky-500/30",
    company: "BookWise",
    industry: "Travel & Hospitality",
    industrySlug: "travel-hospitality",
    headline: "AI-powered travel booking platform with dynamic pricing serving 1M+ bookings annually.",
    challenge: "Aggregating inventory from 200+ suppliers. Dynamic pricing in real-time. Handling peak load during holiday seasons.",
    solution: "Multi-source inventory aggregation with smart caching. ML-based dynamic pricing engine. Auto-scaling infrastructure handling 10x traffic spikes.",
    duration: "90 days",
    Icon: Plane,
    metrics: [
      { value: 1, suffix: "M+", label: "Annual bookings" },
      { value: 200, suffix: "+", label: "Supplier integrations" },
      { value: 15, suffix: "%", label: "Revenue uplift" },
    ],
    timeline: [
      { phase: "Supplier Integration", detail: "200+ API connections, rate normalization" },
      { phase: "Dynamic Pricing", detail: "ML-based demand forecasting, price optimization" },
      { phase: "Search & UX", detail: "Sub-second search, filters, comparison views" },
      { phase: "Scale & Resilience", detail: "Auto-scaling, circuit breakers, CDN" },
    ],
    gradient: "from-sky-600/10 via-transparent to-transparent",
    accentColor: "#0ea5e9",
  },
  {
    id: "hotelops-mgmt",
    tag: "Hotel Management",
    tagColor: "bg-teal-500/15 text-teal-400 border-teal-500/30",
    company: "HotelOps",
    industry: "Travel & Hospitality",
    industrySlug: "travel-hospitality",
    headline: "Smart hotel management system automating operations across 150+ properties.",
    challenge: "Manual check-in/check-out processes. Revenue management across multiple channels. Staff coordination across shifts.",
    solution: "Digital check-in with mobile keys. AI revenue management optimizing room pricing. Staff management with shift scheduling and task tracking.",
    duration: "70 days",
    Icon: ShieldCheck,
    metrics: [
      { value: 150, suffix: "+", label: "Properties managed" },
      { value: 20, suffix: "%", label: "Revenue increase" },
      { value: 50, suffix: "%", label: "Faster check-in" },
    ],
    timeline: [
      { phase: "PMS Core", detail: "Reservation management, room inventory" },
      { phase: "Digital Guest Journey", detail: "Mobile check-in, digital keys, requests" },
      { phase: "Revenue Management", detail: "Dynamic pricing across OTA channels" },
      { phase: "Staff Operations", detail: "Shift scheduling, task management, reporting" },
    ],
    gradient: "from-teal-600/10 via-transparent to-transparent",
    accentColor: "#14b8a6",
  },
  // Enterprise Retail & Manufacturing
  {
    id: "factoryiq-iot",
    tag: "Smart Factory",
    tagColor: "bg-orange-500/15 text-orange-400 border-orange-500/30",
    company: "FactoryIQ",
    industry: "Enterprise Retail & Manufacturing",
    industrySlug: "enterprise-retail-manufacturing",
    headline: "IoT-powered smart factory platform reducing downtime by 45% across 12 production lines.",
    challenge: "Unplanned equipment downtime costing millions. No predictive maintenance capability. Siloed production data.",
    solution: "1000+ IoT sensors for real-time machine monitoring. ML-based predictive maintenance models. Unified production dashboard with OEE tracking.",
    duration: "100 days",
    Icon: Factory,
    metrics: [
      { value: 45, suffix: "%", label: "Downtime reduced" },
      { value: 1000, suffix: "+", label: "IoT sensors" },
      { value: 30, suffix: "%", label: "OEE improvement" },
    ],
    timeline: [
      { phase: "IoT Infrastructure", detail: "Sensor deployment, edge computing setup" },
      { phase: "Data Platform", detail: "Time-series DB, real-time streaming pipeline" },
      { phase: "Predictive Models", detail: "Equipment failure prediction, anomaly detection" },
      { phase: "Dashboard & Alerts", detail: "OEE tracking, automated maintenance alerts" },
    ],
    gradient: "from-orange-600/10 via-transparent to-transparent",
    accentColor: "#f97316",
  },
  {
    id: "retailedge-pos",
    tag: "Retail POS",
    tagColor: "bg-red-500/15 text-red-400 border-red-500/30",
    company: "RetailEdge",
    industry: "Enterprise Retail & Manufacturing",
    industrySlug: "enterprise-retail-manufacturing",
    headline: "Omnichannel POS system unifying 500+ retail stores with real-time inventory.",
    challenge: "Disconnected online and offline sales channels. Inventory discrepancies across stores. Slow checkout experience.",
    solution: "Unified omnichannel POS with offline-first architecture. Real-time inventory sync across all channels. Mobile POS for queue-busting during peak hours.",
    duration: "75 days",
    Icon: Rocket,
    metrics: [
      { value: 500, suffix: "+", label: "Stores unified" },
      { value: 99, suffix: "%", label: "Inventory accuracy" },
      { value: 40, suffix: "%", label: "Faster checkout" },
    ],
    timeline: [
      { phase: "POS Architecture", detail: "Offline-first, multi-store, cloud sync" },
      { phase: "Inventory Engine", detail: "Real-time stock across all channels" },
      { phase: "Omnichannel Integration", detail: "Online, in-store, mobile unification" },
      { phase: "Store Rollout", detail: "Phased deployment, staff training, support" },
    ],
    gradient: "from-red-600/10 via-transparent to-transparent",
    accentColor: "#ef4444",
  },
  // Oil & Gas
  {
    id: "energymon-iot",
    tag: "Energy Monitoring",
    tagColor: "bg-yellow-500/15 text-yellow-400 border-yellow-500/30",
    company: "EnergyMon",
    industry: "Oil & Gas",
    industrySlug: "oil-gas",
    headline: "Real-time pipeline monitoring system preventing leaks across 500km of infrastructure.",
    challenge: "Manual pipeline inspections causing delayed leak detection. Harsh environment sensor challenges. Regulatory compliance reporting.",
    solution: "IoT sensor network along pipeline routes. AI-based anomaly detection for pressure and flow. Automated compliance reporting dashboards.",
    duration: "120 days",
    Icon: Fuel,
    metrics: [
      { value: 500, suffix: "km", label: "Pipeline monitored" },
      { value: 90, suffix: "%", label: "Faster leak detection" },
      { value: 100, suffix: "%", label: "Compliance met" },
    ],
    timeline: [
      { phase: "Sensor Deployment", detail: "Pressure, flow, temperature sensors along pipeline" },
      { phase: "Edge Computing", detail: "On-site data processing, low-latency alerts" },
      { phase: "AI Anomaly Detection", detail: "Pattern recognition for leak prediction" },
      { phase: "Compliance Dashboard", detail: "Automated regulatory reporting" },
    ],
    gradient: "from-yellow-600/10 via-transparent to-transparent",
    accentColor: "#eab308",
  },
  {
    id: "drillsmart-ops",
    tag: "Drilling Operations",
    tagColor: "bg-amber-500/15 text-amber-400 border-amber-500/30",
    company: "DrillSmart",
    industry: "Oil & Gas",
    industrySlug: "oil-gas",
    headline: "AI-optimized drilling operations platform reducing costs by 30% per well.",
    challenge: "Suboptimal drilling parameters causing cost overruns. Equipment failures during operations. Data silos across drilling sites.",
    solution: "ML models optimizing drilling speed, weight-on-bit, and mud properties. Predictive equipment maintenance. Unified operations dashboard across all sites.",
    duration: "90 days",
    Icon: Zap,
    metrics: [
      { value: 30, suffix: "%", label: "Cost per well reduced" },
      { value: 25, suffix: "%", label: "Faster drilling" },
      { value: 50, suffix: "+", label: "Wells optimized" },
    ],
    timeline: [
      { phase: "Data Unification", detail: "Cross-site data pipeline, standardization" },
      { phase: "Drilling ML Models", detail: "Parameter optimization, ROP prediction" },
      { phase: "Equipment Analytics", detail: "Failure prediction, maintenance scheduling" },
      { phase: "Operations Dashboard", detail: "Real-time KPIs, cross-site comparison" },
    ],
    gradient: "from-amber-600/10 via-transparent to-transparent",
    accentColor: "#f59e0b",
  },
  // Media & Entertainment
  {
    id: "streamvault-ott",
    tag: "OTT Platform",
    tagColor: "bg-fuchsia-500/15 text-fuchsia-400 border-fuchsia-500/30",
    company: "StreamVault",
    industry: "Media & Entertainment",
    industrySlug: "media-entertainment",
    headline: "OTT streaming platform with adaptive bitrate serving 2M+ concurrent viewers.",
    challenge: "Buffering issues during peak viewership. Content delivery across geographies. DRM protection for premium content.",
    solution: "ABR streaming with multi-CDN strategy. AI-driven content recommendations. Widevine/FairPlay DRM integration. Real-time viewer analytics.",
    duration: "100 days",
    Icon: Music,
    metrics: [
      { value: 2, suffix: "M+", label: "Concurrent viewers" },
      { value: 99.5, suffix: "%", label: "Stream uptime" },
      { value: 0, suffix: " piracy", label: "DRM protected" },
    ],
    timeline: [
      { phase: "Streaming Infrastructure", detail: "ABR encoding, multi-CDN delivery" },
      { phase: "DRM & Security", detail: "Widevine, FairPlay, content encryption" },
      { phase: "Recommendation Engine", detail: "Watch history, collaborative filtering" },
      { phase: "Analytics & Scale", detail: "Real-time viewer metrics, auto-scaling" },
    ],
    gradient: "from-fuchsia-600/10 via-transparent to-transparent",
    accentColor: "#d946ef",
  },
  {
    id: "podcastpro-audio",
    tag: "Audio Platform",
    tagColor: "bg-violet-500/15 text-violet-400 border-violet-500/30",
    company: "PodcastPro",
    industry: "Media & Entertainment",
    industrySlug: "media-entertainment",
    headline: "Podcast hosting and analytics platform used by 5000+ creators with AI transcription.",
    challenge: "No affordable hosting with detailed analytics. Manual transcription processes. Monetization tools for independent creators.",
    solution: "Scalable audio hosting with per-episode analytics. AI-powered transcription and chapter markers. Built-in sponsorship marketplace for creators.",
    duration: "60 days",
    Icon: Bot,
    metrics: [
      { value: 5000, suffix: "+", label: "Creators" },
      { value: 98, suffix: "%", label: "Transcription accuracy" },
      { value: 3, suffix: "x", label: "Creator revenue" },
    ],
    timeline: [
      { phase: "Hosting Infrastructure", detail: "S3-based storage, RSS feed generation" },
      { phase: "AI Transcription", detail: "Speech-to-text, chapter detection, search" },
      { phase: "Analytics Dashboard", detail: "Downloads, retention, listener demographics" },
      { phase: "Monetization", detail: "Sponsorship marketplace, premium subscriptions" },
    ],
    gradient: "from-violet-600/10 via-transparent to-transparent",
    accentColor: "#8b5cf6",
  },
  // On Demand Delivery
  {
    id: "quickdrop-delivery",
    tag: "Last-Mile Delivery",
    tagColor: "bg-lime-500/15 text-lime-400 border-lime-500/30",
    company: "QuickDrop",
    industry: "On Demand Delivery",
    industrySlug: "on-demand-delivery",
    headline: "Last-mile delivery platform processing 50K+ daily orders with AI route optimization.",
    challenge: "Inefficient last-mile delivery routes. Real-time tracking for customers and drivers. Peak hour demand management.",
    solution: "AI-powered route optimization cutting delivery time by 30%. Real-time GPS tracking with ETA predictions. Dynamic pricing and surge management.",
    duration: "70 days",
    Icon: Package,
    metrics: [
      { value: 50, suffix: "K+", label: "Daily orders" },
      { value: 30, suffix: "%", label: "Faster deliveries" },
      { value: 4.8, suffix: "/5", label: "Customer rating" },
    ],
    timeline: [
      { phase: "Order Management", detail: "Multi-vendor order aggregation, dispatch" },
      { phase: "Route Optimization", detail: "AI routing with traffic and demand data" },
      { phase: "Real-Time Tracking", detail: "GPS tracking, ETA prediction, notifications" },
      { phase: "Surge Management", detail: "Dynamic pricing, demand forecasting" },
    ],
    gradient: "from-lime-600/10 via-transparent to-transparent",
    accentColor: "#84cc16",
  },
  {
    id: "grocerynow-instant",
    tag: "Grocery Delivery",
    tagColor: "bg-green-500/15 text-green-400 border-green-500/30",
    company: "GroceryNow",
    industry: "On Demand Delivery",
    industrySlug: "on-demand-delivery",
    headline: "10-minute grocery delivery app with dark store management and inventory prediction.",
    challenge: "Ultra-fast delivery promise requiring precise inventory. Dark store operations management. Fresh produce quality control.",
    solution: "AI inventory prediction for dark stores. Batched picking optimization. Quality scoring system for fresh produce with IoT temperature monitoring.",
    duration: "85 days",
    Icon: Zap,
    metrics: [
      { value: 10, suffix: " min", label: "Avg delivery time" },
      { value: 95, suffix: "%", label: "Inventory accuracy" },
      { value: 20, suffix: "+", label: "Dark stores" },
    ],
    timeline: [
      { phase: "Dark Store Platform", detail: "Inventory management, picking optimization" },
      { phase: "Demand Prediction", detail: "ML-based stock forecasting per location" },
      { phase: "Delivery Engine", detail: "Rider allocation, route optimization" },
      { phase: "Quality Systems", detail: "IoT temp monitoring, freshness scoring" },
    ],
    gradient: "from-green-600/10 via-transparent to-transparent",
    accentColor: "#22c55e",
  },
  // Home Service
  {
    id: "fixitpro-homeservice",
    tag: "Home Service App",
    tagColor: "bg-teal-500/15 text-teal-400 border-teal-500/30",
    company: "FixItPro",
    industry: "Home Service",
    industrySlug: "home-service",
    headline: "On-demand home service platform connecting 10K+ professionals with homeowners.",
    challenge: "Matching right professionals to service requests. Real-time scheduling and availability. Trust and quality assurance.",
    solution: "AI-powered matching based on skills, ratings, and proximity. Real-time scheduling with calendar integration. Review system with verified service completion.",
    duration: "60 days",
    Icon: Home,
    metrics: [
      { value: 10, suffix: "K+", label: "Professionals" },
      { value: 4.7, suffix: "/5", label: "Avg rating" },
      { value: 15, suffix: " min", label: "Avg response time" },
    ],
    timeline: [
      { phase: "Matching Engine", detail: "Skill, rating, and proximity-based matching" },
      { phase: "Scheduling System", detail: "Real-time availability, calendar sync" },
      { phase: "Trust & Safety", detail: "Background checks, verified reviews" },
      { phase: "Payment & Support", detail: "Escrow payments, dispute resolution" },
    ],
    gradient: "from-teal-600/10 via-transparent to-transparent",
    accentColor: "#14b8a6",
  },
  {
    id: "cleanswift-cleaning",
    tag: "Cleaning Service",
    tagColor: "bg-cyan-500/15 text-cyan-400 border-cyan-500/30",
    company: "CleanSwift",
    industry: "Home Service",
    industrySlug: "home-service",
    headline: "Subscription-based cleaning service platform managing 5000+ recurring bookings monthly.",
    challenge: "Managing recurring bookings and cleaner assignments. Quality consistency across services. Last-minute cancellation handling.",
    solution: "Automated recurring scheduling with smart cleaner rotation. Post-service quality checklist with photo verification. Auto-reassignment for cancellations.",
    duration: "45 days",
    Icon: Rocket,
    metrics: [
      { value: 5000, suffix: "+", label: "Monthly bookings" },
      { value: 98, suffix: "%", label: "Service completion" },
      { value: 92, suffix: "%", label: "Retention rate" },
    ],
    timeline: [
      { phase: "Subscription Engine", detail: "Recurring plans, flexible scheduling" },
      { phase: "Cleaner Management", detail: "Smart rotation, availability tracking" },
      { phase: "Quality Assurance", detail: "Photo checklists, customer feedback loops" },
      { phase: "Auto-Reassignment", detail: "Cancellation handling, backup matching" },
    ],
    gradient: "from-cyan-600/10 via-transparent to-transparent",
    accentColor: "#06b6d4",
  },
  // Fintech
  {
    id: "paybridge-fintech",
    tag: "Payment Gateway",
    tagColor: "bg-indigo-500/15 text-indigo-400 border-indigo-500/30",
    company: "PayBridge",
    industry: "Fintech",
    industrySlug: "fintech",
    headline: "Unified payment gateway processing $500M+ annually with 99.99% uptime.",
    challenge: "Supporting 50+ payment methods across regions. PCI-DSS Level 1 compliance. Sub-200ms transaction processing.",
    solution: "Multi-acquirer routing for optimal success rates. PCI-DSS Level 1 certified infrastructure. Smart retry logic with fallback routing.",
    duration: "100 days",
    Icon: DollarSign,
    metrics: [
      { value: 500, suffix: "M+", label: "Annual volume ($)" },
      { value: 99.99, suffix: "%", label: "Uptime" },
      { value: 150, suffix: "ms", label: "Avg latency" },
    ],
    timeline: [
      { phase: "Gateway Architecture", detail: "Multi-acquirer routing, tokenization" },
      { phase: "PCI Compliance", detail: "Level 1 certification, encryption, audits" },
      { phase: "Smart Routing", detail: "Success rate optimization, retry logic" },
      { phase: "Merchant Dashboard", detail: "Real-time analytics, settlement tracking" },
    ],
    gradient: "from-indigo-600/10 via-transparent to-transparent",
    accentColor: "#6366f1",
  },
  {
    id: "wealthwise-invest",
    tag: "Investment Platform",
    tagColor: "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
    company: "WealthWise",
    industry: "Fintech",
    industrySlug: "fintech",
    headline: "Robo-advisory investment platform managing $200M+ AUM with AI portfolio optimization.",
    challenge: "Automated portfolio rebalancing at scale. Regulatory compliance across jurisdictions. Tax-loss harvesting complexity.",
    solution: "AI-driven portfolio allocation with risk profiling. Automated tax-loss harvesting. Multi-jurisdiction regulatory compliance engine.",
    duration: "90 days",
    Icon: Bot,
    metrics: [
      { value: 200, suffix: "M+", label: "AUM ($)" },
      { value: 12, suffix: "%", label: "Avg annual return" },
      { value: 100, suffix: "%", label: "Compliant" },
    ],
    timeline: [
      { phase: "Risk Profiling", detail: "User questionnaire, risk score algorithm" },
      { phase: "Portfolio Engine", detail: "AI allocation, automated rebalancing" },
      { phase: "Tax Optimization", detail: "Tax-loss harvesting, gain deferral" },
      { phase: "Compliance & Reporting", detail: "Regulatory engine, investor reports" },
    ],
    gradient: "from-emerald-600/10 via-transparent to-transparent",
    accentColor: "#10b981",
  },
  // mCommerce
  {
    id: "mshop-commerce",
    tag: "Mobile Commerce",
    tagColor: "bg-pink-500/15 text-pink-400 border-pink-500/30",
    company: "mShop",
    industry: "mCommerce",
    industrySlug: "mcommerce",
    headline: "Mobile-first commerce app with AR try-on and one-tap checkout serving 2M+ users.",
    challenge: "High cart abandonment on mobile. Lack of product visualization for fashion/beauty. Complex checkout flows on small screens.",
    solution: "AR-powered virtual try-on for products. One-tap checkout with saved payment methods. AI-personalized home feed with push notifications.",
    duration: "75 days",
    Icon: Smartphone,
    metrics: [
      { value: 2, suffix: "M+", label: "Active users" },
      { value: 55, suffix: "%", label: "Less abandonment" },
      { value: 3, suffix: "x", label: "Conversion lift" },
    ],
    timeline: [
      { phase: "Mobile UX Design", detail: "Thumb-friendly navigation, gesture controls" },
      { phase: "AR Try-On", detail: "Camera integration, 3D product rendering" },
      { phase: "One-Tap Checkout", detail: "Saved cards, biometric auth, express pay" },
      { phase: "Personalization", detail: "AI feed, push notifications, recommendations" },
    ],
    gradient: "from-pink-600/10 via-transparent to-transparent",
    accentColor: "#ec4899",
  },
  {
    id: "scanpay-mobile",
    tag: "Scan & Pay",
    tagColor: "bg-rose-500/15 text-rose-400 border-rose-500/30",
    company: "ScanPay",
    industry: "mCommerce",
    industrySlug: "mcommerce",
    headline: "QR-based mobile payment app enabling contactless commerce for 100K+ merchants.",
    challenge: "Fragmented payment ecosystem. Merchant onboarding complexity. Offline payment support in rural areas.",
    solution: "Universal QR code supporting all major wallets. 5-minute merchant self-onboarding. Offline transaction support with sync-when-connected.",
    duration: "55 days",
    Icon: Zap,
    metrics: [
      { value: 100, suffix: "K+", label: "Merchants" },
      { value: 5, suffix: " min", label: "Onboarding time" },
      { value: 10, suffix: "M+", label: "Monthly transactions" },
    ],
    timeline: [
      { phase: "QR Infrastructure", detail: "Dynamic QR generation, universal scanner" },
      { phase: "Merchant Platform", detail: "Self-onboarding, KYC automation" },
      { phase: "Offline Mode", detail: "Transaction queuing, sync-when-connected" },
      { phase: "Analytics & Lending", detail: "Merchant analytics, credit scoring" },
    ],
    gradient: "from-rose-600/10 via-transparent to-transparent",
    accentColor: "#f43f5e",
  },
];
